apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: trading-serviceaccount
      containers:
        - name: trading
          image: playeconomyacr.azurecr.io/play.trading:1.0.3
          securityContext: # temp
            runAsUser: 0
            privileged: true
          env:
            - name: ASPNETCORE_URLS # temp
              value: "http://+:5006"
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: economykeyvault
            - name: ServiceSettings__Authority
              value: https://playeconomy-gateway.westus2.cloudapp.azure.com/identity/svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5006
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5006
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5006
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading
  ports:
    - port: 80
      targetPort: 5006

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
  annotations:
    azure.workload.identity/client-id: 28820185-275e-4d40-8af5-876081c9d34a
  labels:
    azure.workload.identity/use: "true"
